repos:
-   repo: local
    hooks:
    -   id: generate-bash-docs
        name: Generate Bash script documentation
        entry: bash -c 'for file in ./bash/utilities/*.bash; do ./utils/shdoc < "$file" > "./docs/api/bash/$(basename "${file%.bash}").md"; done && git add ./docs/api/bash/*.md'
        language: system
        files: ^bash/utilities/.*\.bash$
        pass_filenames: false
