repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck

-   repo: https://github.com/mvdan/sh
    rev: v3.8.0
    hooks:
    -   id: shfmt
        args: ["-i", "4", "-s"] # Indent with 4 spaces and simplify code