site_name: Scriptize
repo_url: https://github.com/JonathanTSilva/scriptize
repo_name: JonathanTSilva/scriptize
edit_uri: /tree/main/docs

theme:
  name: material
  language: en
  logo: assets/img/scriptize_single_logo.png
  favicon: assets/img/scriptize_single_logo.png

markdown_extensions:
  - attr_list

extra_css:
  - assets/stylesheets/extra.css
