name: Run Tests and Publish Report

on:
  push:
    branches: [ main ] # Runs on pushes to the main branch
  pull_request:
    branches: [ main ] # Runs on pull requests targeting main

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run CI Pipeline (Lint, Typecheck, Test)
        run: poetry run task ci

      - name: Generate and publish Allure Report
        uses: allure-framework/allure-action@v3
        with:
          # This command generates the static HTML report
          report_command: poetry run task post_test
          # This tells the action where the generated report is
          report_dir: allure-report
          # This will publish the report to GitHub Pages
          gh_pages: true
          # A personal access token is required to push to the gh-pages branch
          github_token: ${{ secrets.GITHUB_TOKEN }}
