name: CI & Test Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run CI Pipeline (Lint, Typecheck, Test)
        run: poetry run task ci

      # FIX: Add this step to check out the existing gh-pages branch for history
      - name: Check out gh-pages branch
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true # This allows the workflow to continue if the branch doesn't exist yet
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report with History
        uses: mgrybyk-org/allure-report-branch-js-action@v1
        if: always()
        id: allure_report
        with:
          report_dir: 'test/allure-results'
          gh_pages: 'gh-pages' # This MUST match the 'path' in the step above
          max_reports: 50

      - name: Move report to root of gh-pages
        if: always()
        run: |
          # The report is in a nested folder; find it (its name is dynamic)
          LATEST_REPORT_DIR=$(find gh-pages/allure-action -type d -name "*_*" | head -n 1)
          # Move all of its contents to the root of the gh-pages checkout
          mv $LATEST_REPORT_DIR/* gh-pages/

      - name: Deploy Report to GH Pages
        # This step only runs on pushes to the 'main' branch
        if: always() && github.ref == 'refs/heads/main'
        uses: mgrybyk-org/git-commit-pull-push-action@v1
        with:
          repository: gh-pages # The directory with the checked-out branch
          branch: gh-pages      # The branch to push to
          # This handles potential merge conflicts by favoring the new report
          pull_args: --rebase -X ours

      - name: Comment on Pull Request with Report Link
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ steps.allure_report.outputs.test_result_icon }} **Allure Test Report** is ready!

            * **Report Link:** ${{ steps.allure_report.outputs.report_url }}
            * **History:** ${{ steps.allure_report.outputs.report_history_url }}
          comment_tag: allure_report
